name: gauche
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip=21.1.3
  - jupyterlab=3.0.14
  - botorch
  - selfies
  - scikit-learn
  - pandas
  - pytest
  - tqdm
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip:
    - graphein==1.4.0
    - rdkit
    - torch-geometric == 1.7.2
